USE  watershed;

ALTER TABLE `WATER_QUALITY`
ADD COLUMN `id` INT  AUTO_INCREMENT,
ADD PRIMARY KEY (`id`);

ALTER TABLE WATER_QUALITY CHANGE COLUMN  id id int(11) after SAMPLE_DATE;

ALTER TABLE WATER_QUALITY CHANGE COLUMN  SAMPLE_DATE SAMPLE_DATE date after id;